---
deployment:
  tasks:
    - export DEPLOYPATH=/home/fsena465/public_html
    - /bin/cp /fsenaweb/dist/index.html $DEPLOYPATH
    - /bin/cp -r /fsenaweb/dist/static/* $DEPLOYPATH
    - /bin cp /fsenaweb/dist/service-worker.js $DEPLOYPATH
